FORMAT: 1A
HOST: https://hasvariants.apispark.net/v1

# Contacts API

Contacts and companies API. Test update!

## Questions Collection [/companies]

### List All Companies [GET]

+ Response 200 (application/json)

        [ {
                "id" : "sample id",
                "N@me" : "",
                "tags" : [ "sample tags" ],
                "address" : {
                        "street" : "sample street",
                        "zipcode" : "sample zipcode",
                        "city" : "sample city"
                }
        } ]
